#!/usr/bin/env python
# -*- coding: utf-8 -*-

# ------------------------------------------------------------------------------------------#
# Copyright (c) 2026 Beijing Astragenomics Technology Co., Ltd. All rights reserved.        #
# Licensing: see the LICENSE file in the repository root.                                   #
# version : 1.0                                                                             #
#                                                                                           #
# Author:                                                                                   #
#   Kai Liu <kai.liu@astragenomics.com>                                                     #
#                                                                                           #
# Description:                                                                              #
#   Common method for detecting insertion sites in transposon and retrotransposon assays.   #
#                                                                                           #
# Note:                                                                                     #
#   For special transposition events generated by transposons or retrotransposons, a        #
#   specialized secondary analysis pipeline should be used (e.g. R4_mapping_info_show.py).  # 
# ------------------------------------------------------------------------------------------#

import os
import yaml
from Bio import Seq, SeqIO, SeqRecord
from argparse import ArgumentParser
from function import mkdir
from mapping_function import get_snapgene_seq, compare_plasmid_to_genome, build_bwa_index
from mapping_function import NGS_data_qc, bwa_mem_align
from mapping_instance import screen_insert_event, fragment_classification
from mapping_instance import data_stat, show_data_dupstatus
from bam_alignment_stat import bam_alignment_stat


def parse_params():
    parser = ArgumentParser(description='Mapping analysis for transposons and retrotransposons.')
    parser.add_argument('--fastq', help='NGS PE raw data; .R1.fq and .R2.fq paths are split by comma.', required=True)
    parser.add_argument('--donor', help='donor plasmid (.dna).', required=True)
    parser.add_argument('--donor_label',help='donor plasmid label used in reference.fa. default same as --outlabel')
    parser.add_argument('--exist_index', help='Existing BWA index prefix.', default='')
    parser.add_argument('--bam_ok',help='True: BAM creation steps are already complete. Default False.',default='False',choices=['True','False'])
    parser.add_argument('--primer_homo', help="Coordinates for primer-to-homo (right): primer_5' start, TE_3' end, Homo_3' end (0-based, half-open interval).", default='0,0')
    parser.add_argument('--homo_primer', help='coordinate of primer to homo(Left), like primer_homo but reverse.',default='0,0')
    parser.add_argument('--TSD', help='expected TSD sequence, eg. TTAA, TA. Used when specific TSD sequence is known.', default='')
    parser.add_argument('--TSD_len', help='[Deprecated] expected TSD length, used when <only> TSD length is known.', default=0,type=int) 
    parser.add_argument('--UMI', help='Length of UMI. If no UMI is used, it will be set to 0.', default=0, type=int, required=True)
    parser.add_argument('--config', help='config file in yaml format.', required=True)
    parser.add_argument('--sequenator', help='Sequencing platform used to generate NGS data (Illumina or MGI). [default MGI]', default='MGI',choices=['Illumina','MGI'])
    parser.add_argument('--outpath', help='specify the output directory.', required=True)
    parser.add_argument('--outlabel', help='specify the output file label.', required=True)
    parser.add_argument('--species', help='specify the species of genome.',default='human',
                        choices=['human','mouse'])
    params = parser.parse_args()
    return params


if __name__ == '__main__':
    params = parse_params()
    fastq = params.fastq.split(',')
    donor = params.donor
    TSD = params.TSD
    TSD_len = params.TSD_len
    UMI_length = params.UMI
    config_file = params.config
    outpath = mkdir(params.outpath)
    outlabel = params.outlabel
    if params.donor_label:
        donor_label = params.donor_label
    else:
        donor_label = outlabel
    sequenator = params.sequenator
    species = params.species


    primer_homo = [int(i) for i in params.primer_homo.split(',')]
    homo_primer = [int(i) for i in params.homo_primer.split(',')]
    donor_coordinate = {donor_label: {'Left':homo_primer,'Right':primer_homo}}
    print(donor_coordinate)

    with open(config_file) as fw:
        config = yaml.safe_load(fw)
    tools = config['tool']
    species_config = config['species'][species]

    # compare plasmid with genome, check if there is homologous sequence
    donor_seq = get_snapgene_seq(donor)
    outpath_plasmid = mkdir(os.path.join(outpath,'plasmid'))
    donor_fa_file = f'{outpath_plasmid}/{outlabel}.plasmid.fa'
    donor_seq_record = SeqRecord.SeqRecord(Seq.Seq(donor_seq), id=donor_label, description='')
    SeqIO.write(donor_seq_record, donor_fa_file, format='fasta')
    plasmid_map2genome_file = compare_plasmid_to_genome(tools['blat'], species_config['genome'], donor_fa_file, outpath_plasmid, outlabel)

    # build index
    outpath_index = mkdir(os.path.join(outpath, f'{outlabel}_index'))
    if params.exist_index:
        index_prefix = params.exist_index
    else:
        print('execute: build_bwa_index()')
        index_prefix = build_bwa_index(tools['bwa'], species_config['genome'], donor_fa_file, outpath_index, outlabel)

    if params.bam_ok != 'True':
        outpath_fq = mkdir(os.path.join(outpath, 'fastq'))
        R1, R2, qc_json = NGS_data_qc(tools['umi_tools'],tools['cutadapt'], tools['fastp'], fastq[0], fastq[1], outpath_fq, outlabel,UMI=UMI_length, ME_seq=config['ME'],sequenator=sequenator)

        outpath_align = mkdir(os.path.join(outpath, 'align'))
        print('execute: bwa_mem_align()')
        bam, origin_bam = bwa_mem_align(tools['bwa'], tools['java'], tools['picard'], tools['samtools'],index_prefix, R1, R2, outpath_align, outlabel,UMI=UMI_length)
    else:
        qc_json = os.path.join(outpath, 'fastq', f'{outlabel}.qc.json')
        outpath_align = os.path.join(outpath, 'align')
        bam = os.path.join(outpath_align, f'{outlabel}.04.sort.rmdup.bam')
        origin_bam = os.path.join(outpath_align, f'{outlabel}.03.markdup_picard.bam')

    # transposon insertion site analysis
    outpath_ret = mkdir(os.path.join(outpath,'result'))
    print('execute: screen_insert_event()')
    reads_parse_file =  screen_insert_event(bam,donor_coordinate,index_prefix,outpath_ret,outlabel,TSD,TSD_len)
    print('execute: fragment_classification()')
    fragment_event_file = fragment_classification(
        reads_parse_file, plasmid_map2genome_file, outpath_ret, outlabel)
    # summarize and show
    bam_stat_file = bam_alignment_stat(origin_bam,outpath_align,outlabel)
    data_stat(bam_stat_file,qc_json,fragment_event_file,outpath_ret,outlabel)
    show_data_dupstatus(fragment_event_file,outpath_ret,outlabel)
